import React from 'react'

function EatMe() {
  return (
     /*
    GAME IDEA : 3RD PAGE
    IT IS LIKE SNAKE GAME BUT THE FOOD IS THE IMG OF THE SENDER
    WHEN THE RECIEVER REACH CERTAIN AMOUNT OF FOOD THE GAME WILL END
    IF IT EATS ITSELF THE GAME WILL RESET AND WILL SAY "DONT EAT YOURSELF"
    AFTER COMPLETING THE GAME IT WILL PROCEED TO THE LAST PAGE
  */

    <div>EatMe</div>
  )
}

export default EatMe